oopLan/oopLan/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace oopLan.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

oopLan/oopLan/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Dynamic;
using System.Text.Json;
using System.Text;
using static System.Net.WebRequestMethods;
using labOpp.Model;
using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query;


namespace oopLan.Pages
{
	public class IndexModel : PageModel
	{
		public Guid currentDeletedApplication;

		public List<OutputApplication> applicationsList { get; set; } = new List<OutputApplication>();

		public List<OutputApplication> applicationsOutput { get; set; } = new List<OutputApplication>();

		[BindProperty]
		public string SearchPrompt { get; set; }

		[BindProperty]
		public string DateStart { get; set; }

		[BindProperty]
		public string DateEnd { get; set; }

		public IndexModel()
		{
			OnGet();
		}

		public IActionResult IndexModelRefresh()
		{
			return Page();
		}

		public async Task OnPostDeleteApplication(Guid applicationID)
		{
			currentDeletedApplication = applicationID;

			using (HttpClient client = new HttpClient())
			{
				var response = await client.DeleteAsync($"https://localhost:7096/DeleteApplication?applicationID={applicationID}");
			}
			IndexModelRefresh();
		}

		public async Task OnPostSearchApplications()
		{
			await OnGet();
			if (SearchPrompt != null)
			{
				ViewData["lastSearch"] = SearchPrompt;

				var applicationsSearch = from app in applicationsList
										 where (app.Title.Contains(SearchPrompt, StringComparison.CurrentCultureIgnoreCase) ||
										 app.Activity.Contains(SearchPrompt, StringComparison.CurrentCultureIgnoreCase) ||
										 app.ShortDescription.Contains(SearchPrompt, StringComparison.CurrentCultureIgnoreCase) ||
										 app.Plan.Contains(SearchPrompt, StringComparison.CurrentCultureIgnoreCase) ||
										 app.Platform.Contains(SearchPrompt, StringComparison.CurrentCultureIgnoreCase))
										 select app;

				applicationsList = applicationsSearch.ToList();
			}

			if (DateStart != null || DateEnd != null)
			{
				DateTime dateStart, dateEnd;

				bool dateParsedStart = DateTime.TryParse(DateStart, out dateStart);
				bool dateParsedEnd = DateTime.TryParse(DateEnd, out dateEnd);

				ViewData["lastDateStart"] = dateParsedStart ? dateStart.ToString("yyyy-MM-dd") : null;
				ViewData["lastDateEnd"] = dateParsedEnd ? dateEnd.ToString("yyyy-MM-dd") : null;

				var applications = from app in applicationsList
								   where (app.SubmissionDate >= dateStart &&
								   app.SubmissionDate <= dateEnd)
								   select app;
				applicationsList = applications.ToList();
			}
		}


		public async Task OnGet()
		{
			try
			{
				using (HttpClient _http = new HttpClient())
				{

					applicationsList = await _http.GetFromJsonAsync<List<OutputApplication>>("https://localhost:7096/OutputApplications");

					Console.WriteLine(applicationsList.Count());
				}
			}
			catch (Exception ex)
			{

			}
		}

	}
}

oopLan/oopLan/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace oopLan.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

oopLan/oopLan/Pages/Registration.cshtml.cs
using labOpp.Model;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net;
using System.Text;
using System.Text.Json;
using System.Xml.Linq;


namespace oopLan.Pages
{
    public class RegistrationModel : PageModel
    {

		[BindProperty]
		public string userName { get; set; }

		[BindProperty]
		public string userEmail { get; set; }

		public HttpStatusCode responseStatusCode;

		public void OnGet()
        {

        }

		public async Task OnPostAddAccount()
		{
			var content = new StringContent(userName, Encoding.UTF8, "application/json");

			using (HttpClient client = new HttpClient())
			{
				var response = await client.PostAsync($"https://localhost:7096/CreateNewUser?name={userName}&mail={userEmail}", content);
				responseStatusCode = response.StatusCode;
				if (responseStatusCode != System.Net.HttpStatusCode.Created)
				{
					ViewData["Message"] = "OLIIbIBKA! Eta pochta uzhe zanyata. Vvedite druguyu";
				}
				Console.WriteLine(responseStatusCode);
            }
		}
	}
}

oopLan/oopLan/Pages/CreateApplication.cshtml
@page
@model oopLan.Pages.CreateApplicationModel
@{
	ViewData["Title"] = "Create Application";
}
<div class="create-application-block">

	<form class="create-application" method="post" asp-page-handler="CreateNewApplication">
		<label>Имя</label>
		<p><input class="input-text" type="text" maxlength="48" name="userName" autocomplete="off" required></p>
		<label>Email</label>
		<p><input class="input-text" type="email" name="userEmail" autocomplete="off" required /></p>
		<label>Название</label>
		<p><input class="input-text" type="text" maxlength="48" name="applicationName" autocomplete="off" required /></p>
		<label>Тип активности</label>
		<p><select class="input-text"  name="applicationActivity" required >
				@foreach (var activity in Model.activities)
				{
					<option value="@activity.ActivityID"> @activity.Name </option>
				}
		</select></p>
		<label>Платформа проведения</label>
		<p>
			<select class="input-text" name="applicationPlatform" required>
				@foreach (var platform in Model.platforms)
				{
					<option value="@platform.PlatformId"> @platform.Name </option>
				}
			</select>
		</p>
		<label>Описание</label>
		<p><textarea class="input-description" name="applicationDescription" autocomplete="off" required></textarea></p>
		<label>Дата проведения</label>
		<p><input type="date" class="date-field" min="@Model.currentDate" name="datePlan" /></p>
		<p>
			<button class="input-button search-button" type="submit">Создать</button>
		</p>
	</form>
</div>

oopLan/oopLan/Pages/Index.cshtml
@page 
@model IndexModel
@{
	ViewData["Title"] = "Applications";
}

<div>
	<form class="search-block" method="post" asp-page-handler="SearchApplications">
		<input type="search" class="search-field" name="searchPrompt" placeholder="Поле поиска" value="@ViewData["lastSearch"]" />
		<label class="search-label">от</label>
		<input type="date" class="date-field" name="dateStart" value="@ViewData["lastDateStart"]"/>
		<label class="search-label">до</label>
		<input type="date" class="date-field" name="dateEnd" value="@ViewData["lastDateEnd"]" />
		<button type="submit" class="input-button search-button">Поиск</button>
		<button class="search-button update-button material-icons" style="font-size:32px;" action="@Model.IndexModelRefresh()">refresh</button>
	</form>
	

	<table data="Applications">
		<thead>
			<tr>
				<th scope="col">Название</th>
				<th scope="col">Автор</th>
				<th scope="col">Тип активности</th>
				<th scope="col">Описание</th>
				<th scope="col">Платформа</th>
				<th scope="col">Дата</th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var application in Model.applicationsList)
			{
					<tr>
						<th scope="row">@application.Title</th>
						<td>@application.Author</td>
						<td>@application.Activity</td>
						<td>@application.ShortDescription</td>
						<td>@application.Platform</td>
						<td>@application.SubmissionDate.ToString("dd.MM.yyyy")</td>
					<td>
						<form method="post" asp-page-handler="DeleteApplication">
							<input type="hidden" name="applicationId" value="@application.ApplicationId" />
							<button type="submit" class="delete-button @(Model.currentDeletedApplication==@application.ApplicationId ? "application-deleted": "")">+</button>
						</form>
					</td>
					</tr>
			}
		</tbody>
	</table>


</div>

oopLan/oopLan/Pages/Registration.cshtml
@page
@model oopLan.Pages.RegistrationModel
@{
	ViewData["Title"] = "Registration";
}
<div class="create-application-block">

	<form class="create-application" method="post">
		<label>Имя</label>
		<p><input class="input-text" type="text" maxlength="48" name="userName" autocomplete="off" required></p>
		<label>Email</label>
		<p><input class="input-text" type="email" name="userEmail" autocomplete="off" required /></p>
		
		<p>
			<button action="@Model.AddAccount()" class="input-button search-button" type="submit">Создать</button>
		</p>
	</form>




</div>

oopLan/oopLan/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - oopLan</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/oopLan.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand">Конференции</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark @((string?)ViewData["Title"]=="Applications" ? "active": "")" asp-area="" asp-page="/Index">Заявки</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark @((string?)ViewData["Title"]=="Create Application" ? "active": "")" asp-area="" asp-page="/CreateApplication">Создать заявку</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark @((string?)ViewData["Title"]=="Registration" ? "active": "")" asp-area="" asp-page="/Registration">Создать пользователя</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<div class="backwrap gradient">
		<div class="back-shapes">
			<span class="floating circle" style="top:66.59856996935649%;left:13.020833333333334%;animation-delay:-0.9s;"></span>
			<span class="floating triangle" style="top:31.46067415730337%;left:33.59375%;animation-delay:-4.8s;"></span>
			<span class="floating cross" style="top:76.50663942798774%;left:38.020833333333336%;animation-delay:-4s;"></span>
			<span class="floating square" style="top:21.450459652706844%;left:14.0625%;animation-delay:-2.8s;"></span>
			<span class="floating square" style="top:58.12053115423902%;left:56.770833333333336%;animation-delay:-2.15s;"></span>
			<span class="floating square" style="top:8.682328907048008%;left:72.70833333333333%;animation-delay:-1.9s;"></span>
			<span class="floating cross" style="top:31.3585291113381%;left:58.541666666666664%;animation-delay:-0.65s;"></span>
			<span class="floating cross" style="top:69.96935648621042%;left:81.45833333333333%;animation-delay:-0.4s;"></span>
			<span class="floating circle" style="top:15.117466802860061%;left:32.34375%;animation-delay:-4.1s;"></span>
			<span class="floating circle" style="top:13.074565883554648%;left:45.989583333333336%;animation-delay:-3.65s;"></span>
			<span class="floating cross" style="top:55.87334014300306%;left:27.135416666666668%;animation-delay:-2.25s;"></span>
			<span class="floating cross" style="top:49.54034729315628%;left:53.75%;animation-delay:-2s;"></span>
			<span class="floating cross" style="top:34.62717058222676%;left:49.635416666666664%;animation-delay:-1.55s;"></span>
			<span class="floating cross" style="top:33.19713993871297%;left:86.14583333333333%;animation-delay:-0.95s;"></span>
			<span class="floating square" style="top:28.19203268641471%;left:25.208333333333332%;animation-delay:-4.45s;"></span>
			<span class="floating circle" style="top:39.7344228804903%;left:10.833333333333334%;animation-delay:-3.35s;"></span>
			<span class="floating triangle" style="top:77.83452502553627%;left:24.427083333333332%;animation-delay:-2.3s;"></span>
			<span class="floating triangle" style="top:2.860061287027579%;left:47.864583333333336%;animation-delay:-1.75s;"></span>
			<span class="floating triangle" style="top:71.3993871297242%;left:66.45833333333333%;animation-delay:-1.25s;"></span>
			<span class="floating triangle" style="top:31.256384065372828%;left:76.92708333333333%;animation-delay:-0.65s;"></span>
			<span class="floating triangle" style="top:46.47599591419816%;left:38.90625%;animation-delay:-0.35s;"></span>
			<span class="floating cross" style="top:3.4729315628192032%;left:19.635416666666668%;animation-delay:-4.3s;"></span>
			<span class="floating cross" style="top:3.575076608784474%;left:6.25%;animation-delay:-4.05s;"></span>
			<span class="floating cross" style="top:77.3237997957099%;left:4.583333333333333%;animation-delay:-3.75s;"></span>
			<span class="floating cross" style="top:0.9193054136874361%;left:71.14583333333333%;animation-delay:-3.3s;"></span>
			<span class="floating square" style="top:23.6976506639428%;left:63.28125%;animation-delay:-2.1s;"></span>
			<span class="floating square" style="top:81.30745658835546%;left:45.15625%;animation-delay:-1.75s;"></span>
			<span class="floating square" style="top:60.9805924412666%;left:42.239583333333336%;animation-delay:-1.45s;"></span>
			<span class="floating square" style="top:29.009193054136876%;left:93.90625%;animation-delay:-1.05s;"></span>
			<span class="floating square" style="top:52.093973442288046%;left:68.90625%;animation-delay:-0.7s;"></span>
			<span class="floating square" style="top:81.51174668028601%;left:83.59375%;animation-delay:-0.35s;"></span>
			<span class="floating square" style="top:11.542390194075587%;left:91.51041666666667%;animation-delay:-0.1s;"></span>
		</div>
	</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>